#! /bin/bash

osname="$(uname -s)"

case "${osname}" in
  Linux*)
    sudo apt-get -y install keepassx
    sudo apt-get -y install git
    sudo apt-get -y install emacs
    sudo apt-get -y install autojump
    ;;
esac
